lidofinance/alerting-forta

- src/agent-beth-rewards.ts
- src/agent-lido-oracle.ts
- src/constants.ts
Calculate and report the difference between the resulting stETH/UST price and the one obtained from Chainlink feeds.
> Calculate bETH rewards sell slippage

- src/agent.ts
Sending block alerts as transaction ones was a workaround for Defender failing on any block alert, which should be fixed by now.
> Send block-generated alerts as block ones

- src/agent.ts
Currently, if, after agent startup, Forta calls `handleBlock` and then `handleTransaction` without waiting for `handleBlock` to finish (or the other way round), then the logic of the latter may be executed before initialization is complete. This commit fixes it.
> Always wait for initialization in block/tx handlers

- src/agent.ts
https://www.notion.so/Fix-Forta-based-monitoring-48d03fd27424412b833f827511dba18c
Published to test agent https://explorer.forta.network/agent/0x219fcef9d4e4c040b1dd2feb61d5513e6957420b5f25d690e39a78004330af86
> Fix Forta based monitoring

- src/agent-beth-rewards.ts
Add fallback call of lastLiquidationTime before firing BETH-REWARDS-OVERDUE alert
> Add fallback call to AgentBethRewards

- polygon/src/agent-node-operators.ts
+ update existing alerts logics
> Add NO-ACTIVE-NODE-OPERATORS-POLYGON alert

- ethereum/src/agent-pools-rewards.ts
Make block handler calls in agent-pools-rewards.ts async
Motivation:
Make calls faster to avoid time difference in alert emitting
> Make pools handling async

- polygon/src/agent-dao-ops.ts
Use local var for severity storage
so that severity bump will be applied only ones
> fix: Global alerts severity change

- lido-rewards/src/agent-reward-programs.ts
Set monthly rewards limit to 15M LDO
> feat: Update monthly rewards limit

- polygon/src/agent-dao-ops.ts
- polygon/src/constants.ts
Now HUGE-BUFFERED-MATIC alert will be produced only
if huge buffered amount is present for more than 1 hour
> feat: Add wait before HUGE-BUFFERED-MATIC alert

- ethereum/src/agent-proxy-watcher.ts
- ethereum/src/agent.ts
- ethereum/src/constants.ts
Alert is produced if the result of the 'implementation' function call
has changed compared to the previous block
> feat: Add PROXY-IMPL-CHANGED alerts

- ethereum/src/agent-lido-oracle.ts
- ethereum/src/constants.ts
Emitted when oracle balance gets below 0.3 ETH.
Will be repeated every 3 days
> feat: Add LIDO-ORACLE-LOW-BALANCE alert

- ethereum/README.md
- ethereum/src/agent-aragon-voting.ts
- ethereum/src/constants.ts
Add ARAGON-VOTE-STARTED and ARAGON-VOTE-EXECUTED alerts
Tested on
0xe1653e4327bf739a5692a55fca27167911cfd4828dab2e44292c301cc0903a4f (ExecuteVote)
0x46ca637c7b1edfaed7c38ccddcf96f227054bff0a886ed337796836d54340c92 (StartVote)
> feat: Extend Aragon alerts

- phishing-detect/src/agent-phishing-detect.ts
Receipt is not available in some cases, so it's ok
> Catch receipt getting error

- ethereum-operations/src/agent-lido-oracle.ts
Fixing issue with the invalid oracle report data when bot restarts right after the report event
See https://t.me/c/1167753683/1144
> fix: Invalid oracle report info

- ethereum-huge-tx/src/agent-huge-tx.ts
- ethereum-huge-tx/src/constants.ts
Alert only about > 1 000 000 LDO
> feat: Separate threshold for LDO transfers

- ethereum-operations/src/constants.ts
Deposit Security module implementation changed via Aragon Vote #131
```
❯ yarn run tx 0x105d90f342b8cc57cdfe4d1515fdc7e534bdcf814108bb2ef7efe74894866c37
initializing agent...
<...>
3 findings for transaction 0x105d90f342b8cc57cdfe4d1515fdc7e534bdcf814108bb2ef7efe74894866c37 {
"name": "Aragon: Vote executed",
"description": "Aragon vote 131 was executed",
"alertId": "ARAGON-VOTE-EXECUTED",
"protocol": "ethereum",
"severity": "Info",
"type": "Info",
"metadata": {
"args": "131",
"version.commitHash": "865ab069fc80d5c71c881fb777ca5f183c8b16c2"
},
"addresses": []
},{
"name": "Aragon ACL: Permission granted",
"description": "Role 0x2561bf26f818282a3be40719542054d2173eb0d38539e8a8d3cff22f29fd2384 (DEPOSIT ROLE) on the app 0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84 (stETH token) was granted to …
```
> Fix deposit security module monitoring

- phishing-detect/src/constants.ts
[proof](https://github.com/paraswap/paraswap-dex-lib/blob/69e1126de4fe1f63a4df300cdc2f0a1b09db923f/src/dex/augustus-rfq.ts#L67)
> Add paraswap contract to whitelist

- ethereum-huge-tx/src/constants.ts
Test
`yarn tx 0xf9ff5fbfe97f800bc0e5b75e1312b47e5498e5a2808993b5ed308ae8922eab97` – withdrawal
`yarn tx 0x63dfd683fa4ae942fd07b9e0c0a9d19b36261a1ac6b42198af84cf5e3be1c70a` – deposit
> feat: Convex Deposit/Withdrawal

- phishing-detect/src/constants.ts
[Proof](https://github.com/Gearbox-protocol/dev-docs/blob/e9087244c3f18f0eeb74d23a60cbee4e0bb3093f/docs/documentation/deployments/deployed-contracts.md?plain=1#L43)
> chore: add to Gearbox Gateway to WL

- phishing-detect/src/constants.ts
Via deployer address, [proof](https://github.com/curvefi/curve-xchain-factory/blob/6066c873713c50c6baaacad460b7be48fbd45846/redeploy_data.csv#L4)
> chore: add Curve contract to WL

- ethereum-operations/src/agent-lido-oracle.ts
- ethereum-operations/src/constants.ts
Now we will report sloppy oracles on every `Completed` event
> feat: New Sloppy Oracle alert logic

- phishing-detect/src/constants.ts
SY-wstETH-WETH BalancerLP Aura by pendle.finance => [proof](https://github.com/pendle-finance/documentation/blob/a6958d085261f85c06f41c50925369143c10fd4f/docs/PendlePro/Guides/UnwrappingSY.md?plain=1#L20)
> chore: add SY-wstETH-WETH BalancerLP Aura

- phishing-detect/src/constants.ts
[Proof](https://etherfi.gitbook.io/etherfi/deployed-contracts)
> chore: add etherfi contract to WL

- phishing-detect/src/constants.ts
[Pendle](https://github.com/pendle-finance/documentation/blob/32a6f2d029f273fbd5c9a80fea6c0a670f682c0b/docs/Developers/DeployedContracts/Ethereum.md?plain=1#L18) and [Pods](https://github.com/pods-finance/yield-contracts/blob/c73c0678e969c8bd6ab08503f91a5e040258eaad/README.md?plain=1#L176)
> chore: upd-wl

- phishing-detect/src/constants.ts
[revision](https://github.com/sushiswap/sushiswap/blame/5963cffeccacfeb92c9a42b92cdddc312e9eb842/protocols/route-processor/contracts/RouteProcessor.sol)
> chore: add sushi pool

- phishing-detect/src/constants.ts
Matched by the deployer's address.
> chore: add 0x7b0Eff0C991F0AA880481FdFa5624Cb0BC9b10e1 to WL

- phishing-detect/src/constants.ts
[Proof](https://github.com/OriginProtocol/origin-dollar/blob/7e6b66c3cdb21ab7b72b59f305ca3b4b8b5ba4df/brownie/addresses.py#L32) and [proof](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/e77fc7db15b0f21c2a9b732713fdd6f30a7ddab3/scripts/deployment/output/mainnet.json#L16)
> chore: update WL

- phishing-detect/src/constants.ts
[mimic.fi](https://github.com/mimic-fi/v2-deployments/blob/7fe4a74db66dfe0bc7bf2a1f8613888f0496fd69/tasks/2023032700-public-swapper/output/bsc.json#L5) & [curve.fi](https://github.com/curvefi/curve-stablecoin/blob/269c0fa223aa58d2e81c6789785a091f8065c646/scripts/ape-steth-oracle.py#L26)
> chore: update phishing-detect WL

- reverted-tx-watcher/src/agent-reverted-tx.ts
> Reverts mistakes

- ethereum-operations/e2e/__snapshots__/agent-vaults.e2e-spec.ts.snap
- ethereum-operations/src/subagents/accounting-oracle/agent-accounting-hash-consensus.ts
- ethereum-operations/src/subagents/accounting-oracle/constants.ts
- ethereum-operations/src/subagents/exitbus-oracle/agent-exitbus-hash-consensus.ts
- ethereum-operations/src/subagents/exitbus-oracle/constants.ts
- ethereum-operations/src/subagents/vaults/agent-vaults.ts
- ethereum-operations/src/subagents/vaults/constants.ts
chore: Disable "Consensus reached" and "Report Submitted" alerts
chore: Tweak vaults balance alerts severity
> Yet another tweaks

- phishing-detect/src/constants.ts
[Proof](https://github.com/curvefi/curve-stablecoin-js/blob/7da8e399590219fa8dcbd1b9c05391543dbe2b87/src/constants/llammas.ts#L22)
> chore: update constants.ts

- ethereum-huge-tx/src/subagents/huge-tx/constants.ts
Added new Lybra finance pattern for alerting
> Add Lybra finance alert to constants

- ethereum-huge-tx/src/subagents/huge-tx/constants.ts
Added a new Spark protocol to alerting, text transactions:
For withdrawals - 0x84a10807fef72397b72e211a9bc732e5cac2adda5b8226d8fe0a4a435a82e654
For supply - 0x4d615c3f32dcc883b3261facbaf56ce6746f9ede99b1f8fad6d5959329d59462
> Add Spark protocol

- ethereum-huge-tx/src/subagents/huge-tx/constants.ts
Added and tested Lybra finance v2 vaults for stETH and wstETH
> Add Lybra v2 waults

- multisig-watcher/src/constants.ts
Update multisigs with current documentation
https://docs.lido.fi/deployed-contracts/#liquidity-observation-lab-formerly-known-as-rewards-committee-multisigs
> Update multisigs with current docs

- phishing-detect/src/constants.ts
- Solidly one created via SolidlyV3Factory, see [here](https://docs.solidly.com/resources/contract-addresses)
- Blast [proof](https://github.com/l2beat/l2beat/blob/3879dabd765f66eb976c039fb58d715ba10c4df4/packages/backend/discovery/blast/ethereum/config.jsonc#L7)
> chore: update whitelist

- .github/workflows/checks.yml
Pin version for prettier npm package to avoid potential security issues
> Pin version for prettier npm package

- ethereum-validators-set/src/common/constants.ts
- ethereum-validators-set/src/common/utils.ts
- ethereum-validators-set/src/subagents/accounting-oracle/agent-accounting-hash-consensus.ts
- ethereum-validators-set/src/subagents/accounting-oracle/agent-accounting-oracle.ts
- ethereum-validators-set/src/subagents/exitbus-oracle/agent-exitbus-hash-consensus.ts
- ethereum-validators-set/src/subagents/exitbus-oracle/agent-exitbus-oracle.ts
- ethereum-validators-set/src/subagents/lido-report/agent-lido-report.ts
Updated only for ethereum-validator-set bot
> feat: Fetch logs in small chunks to operate on community nodes

- l2-bridge-mantle/jest.config.js
- l2-bridge-mantle/package.json
- l2-bridge-mantle/src/app.ts
- l2-bridge-mantle/src/clients/mantle_provider.ts
- l2-bridge-mantle/src/services/mantle_block_service.ts
- l2-bridge-mantle/src/utils/mutex.ts
- l2-bridge-mantle/src/workers/proxy_watcher.ts
- l2-bridge-mantle/tests/e2e/mantle_provider.spec.ts
- l2-bridge-mantle/tsconfig.json
> feat: l2-mantle fix fetch blocks

- ethereum-validators-set/src/subagents/accounting-oracle/constants.testnet.ts
- ethereum-validators-set/src/subagents/accounting-oracle/constants.ts
- ethereum-validators-set/src/subagents/exitbus-oracle/constants.testnet.ts
- ethereum-validators-set/src/subagents/exitbus-oracle/constants.ts
Addresses could be checked here
https://www.notion.so/f6dc3daff84d4607988bfc0eaac21431?v=27e29eee7af94d7b85f3bc043ab07f15
> Change Oracle members

- l2-bridge-linea/.gitignore
- l2-bridge-linea/src/clients/linea_provider.ts
- l2-bridge-linea/src/services/linea_block_service.ts
> feat: fix linea fetch blocks

- l2-bridge-mantle/src/agent.ts
* fix getting blockNumbers for proxyWatcher
> fix: argument blockNumbers in manle proxyWatcher

- l2-bridge-linea/src/clients/linea_provider.ts
- l2-bridge-linea/src/clients/proxy_contract_client.ts
- l2-bridge-linea/tests/linea_client.spec.ts
- l2-bridge-linea/tsconfig.json
* fix delays (warnings on screenshot)
> fix: delays in l2-linea

- ethereum-validators-set/e2e/__snapshots__/agent-node-operators-registry.e2e-spec.ts.snap
- ethereum-validators-set/e2e/agent-node-operators-registry.e2e-spec.ts
- ethereum-validators-set/e2e/utils.ts
- ethereum-validators-set/src/subagents/node-operators-registry/agent-node-operators-registry.ts
See details here: https://linear.app/lidofi/issue/VAL-743/operator-name-is-not-shown
> fix(val-743): Operator name is not shown

- ethereum-governance/src/subagents/stonks-order-watcher/constants.ts
- ethereum-governance/src/subagents/stonks-order-watcher/stonks-order-watcher.ts
Fixed a few stonks alerts titles
> fix: changed stocks alerts titles

- ethereum-steth/src/app.ts
- ethereum-steth/src/services/vault/Vaults.functional.spec.ts
> fix: ethSteh getting balance by blockHash. Switched to drpc provider

- ethereum-steth/README.md
- ethereum-steth/src/services/gate-seal/GateSeal.srv.ts
- ethereum-steth/src/services/gate-seal/gate-seal.spec.ts
- ethereum-steth/src/services/vault/Vaults.functional.spec.ts
Fixes new gate seal instance [alert](https://explorer.forta.network/alert/0xef9117ff7a6cd4dc25712de44ad2afa2999e58d698410188b1a42332c5e5146b).
> Fix: change gate seal new instance alert

- ethereum-steth/src/services/withdrawals/Withdrawals.functional.spec.ts
- ethereum-steth/src/services/withdrawals/Withdrawals.srv.ts
> Fix: withdrawals wait time text fix

- ethereum-validators-set/e2e/agent-set-ops.e2e-spec.ts
- ethereum-validators-set/e2e/utils.ts
- ethereum-validators-set/src/subagents/set-ops/agent-set-ops.ts
- ethereum-validators-set/src/subagents/set-ops/constants.holesky.ts
- ethereum-validators-set/src/subagents/set-ops/constants.ts
See details here: https://linear.app/lidofi/issue/VAL-740/simpledvt-address-for-setops-subagent-missed
> fix(val-740): SimpleDVT address for setops subagent missed

- ethereum-validators-set/src/subagents/exitbus-oracle/agent-exitbus-oracle.ts
See details here: https://linear.app/lidofi/issue/VAL-877/wrong-node-operator-names-in-the-forta-alert
> fix(val-877): Wrong Node operator names in the forta alert

- l2-bridge-ethereum/src/constants.ts
https://github.com/lidofinance/alerting-forta/issues/556
> fix: Proxy admin for L1 TokenBridge to Linea was changed

- ethereum-validators-set/src/subagents/splitter-wrapper/agent-splitter-wrapper.ts
See details here: https://linear.app/lidofi/issue/VAL-956/[forta-alerts]-bug-in-validation-of-percent-allocation
> fix(val-956): bug in validation of percent allocation

- l2-bridge-ethereum/src/constants.ts
This PR contains an addition of new alert for CrossChainController, which is a part of a.DI contracts set
Links: [LIP-24](https://github.com/lidofinance/lido-improvement-proposals/blob/develop/LIPS/lip-24.md), [a.DI repo](https://github.com/lidofinance/aave-delivery-infrastructure)
> Add a.DI CrossChainController event

- ethereum-huge-tx/src/subagents/huge-tx/constants.ts
New alerts for mellow vaults transactions and addresses of LRTs
> Added Mellow vaults and RST tokens

- bsc-adi-governance/README.md
- bsc-adi-governance/jest.config.js
- bsc-adi-governance/package.json
- bsc-adi-governance/src/clients/bsc_provider.ts
- bsc-adi-governance/src/services/cross-chain-controller/CrossChainController.srv.spec.ts
- bsc-adi-governance/src/services/cross-chain-controller/CrossChainController.srv.ts
- bsc-adi-governance/src/services/cross-chain-controller/__snapshots__/CrossChainController.srv.spec.ts.snap
- bsc-adi-governance/src/services/event-watcher/EventWatcher.srv.spec.ts
- bsc-adi-governance/src/services/event-watcher/__snapshots__/EventWatcher.srv.spec.ts.snap
- bsc-adi-governance/src/utils/constants.ts
- bsc-adi-governance/src/utils/events/cross_chain_controller_events.ts
- bsc-adi-governance/src/utils/events/cross_chain_executor_events.ts
- bsc-adi-governance/yarn.lock
> feat: a.di add events to notice, add tests

- bsc-adi-governance/README.md
- bsc-adi-governance/src/agent.ts
- bsc-adi-governance/src/app.ts
- bsc-adi-governance/src/clients/bsc_provider.ts
- bsc-adi-governance/src/services/acl-changes/AclChanges.srv.spec.ts
- bsc-adi-governance/src/services/acl-changes/AclChanges.srv.ts
- bsc-adi-governance/src/services/acl-changes/__snapshots__/AclChanges.srv.spec.ts.snap
- bsc-adi-governance/src/services/cross-chain-controller/CrossChainController.srv.ts
- bsc-adi-governance/src/utils/constants.ts
- bsc-adi-governance/src/utils/string.ts
- ethereum-governance/src/services/acl-changes/AclChanges.srv.ts
add bsc owner watcher
add test to bsc bot
fix bug in eth-gov bot
> feat: bsc owner watcher, fix bug in ethereum-governance bot

- ethereum-steth/src/clients/eth_provider.spec.ts
- ethereum-steth/src/clients/eth_provider.ts
- ethereum-steth/src/entity/storage_slot.ts
- ethereum-steth/src/handlers/init.handler.ts
- ethereum-steth/src/main.ts
- ethereum-steth/src/services/health-checker/health-checker.srv.ts
- ethereum-steth/src/services/storage-watcher/StorageWatcher.srv.ts
- ethereum-steth/src/utils/constants.ts
> Steth storage watcher

- ethereum-validators-set/package.json
- ethereum-validators-set/src/subagents/splitter-wrapper/agent-splitter-wrapper.spec.ts
- ethereum-validators-set/src/subagents/splitter-wrapper/agent-splitter-wrapper.ts
- ethereum-validators-set/src/subagents/splitter-wrapper/constants.holesky.ts
- ethereum-validators-set/src/subagents/splitter-wrapper/constants.ts
See details here https://linear.app/lidofi/issue/VAL-1188/%5Bsdvt%5D-forta-or-tweak-alerts-for-superclusters
> feat(val-1188): Tweak alerts for superclusters

- ethereum-validators-set/e2e/__snapshots__/agent-node-operators-registry.e2e-spec.ts.snap
- ethereum-validators-set/e2e/agent-node-operators-registry.e2e-spec.ts
- ethereum-validators-set/package.json
- ethereum-validators-set/src/subagents/node-operators-registry/agent-node-operators-registry.ts
- ethereum-validators-set/src/subagents/node-operators-registry/utils.ts
- ethereum-validators-set/yarn.lock
https://linear.app/lidofi/issue/VAL-1199/forta-alerts-reward-address-alert-does-not-work
> fix(val-1199): reward address alert does not work

- ethereum-governance/src/services/aragon-voting/AragonVoting.spec.ts
- ethereum-governance/src/services/aragon-voting/AragonVoting.srv.ts
- ethereum-governance/src/shared/constants/aragon-voting/mainnet.ts
- Update alert description
- Add list of public delegates
> Update on-chain delegation alert

- ethereum-validators-set/src/subagents/accounting-oracle/constants.ts
- ethereum-validators-set/src/subagents/exitbus-oracle/constants.ts
Address could be checked in:
https://etherscan.io/address/0xd624b08c83baecf0807dd2c6880c3154a5f0b288#readContract#F16
And:
https://www.notion.so/f6dc3daff84d4607988bfc0eaac21431?v=27e29eee7af94d7b85f3bc043ab07f15
> Update Instadapp Oracle address
